# Generated by Django 5.0.1 on 2024-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AddField(
            model_name='photo',
            name='detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作品名'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='area',
            field=models.ManyToManyField(max_length=1, to='portfolio.area', verbose_name='撮影場所'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/portfolio/photo/', verbose_name='作品'),
        ),
    ]
